# Generated by Django 4.2.6 on 2024-03-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tach1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
