# Generated by Django 4.2.8 on 2024-03-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jury',
            new_name='Jery',
        ),
    ]
