# Generated by Django 4.2.8 on 2024-03-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_jury_jery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='administrater',
        ),
    ]
