# Generated by Django 4.2.8 on 2024-03-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_défi_id_alter_inscription_id_alter_résultat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='équipe',
            name='nombreMembres',
        ),
    ]
