# Generated by Django 5.0.2 on 2024-03-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_défi_desc_remove_défi_chemin_file_and_more'),
        ('main', '0004_etudiant_jery_remove_utilisateur_niveau_and_more'),
    ]

    operations = [
    ]
