# Generated by Django 5.0.2 on 2024-03-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20240317_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
