# Generated by Django 5.0.2 on 2024-03-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tach3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='défi',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='défi',
            name='chemin_file',
        ),
        migrations.RemoveField(
            model_name='défi',
            name='nom_file',
        ),
        migrations.AddField(
            model_name='défi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
